### ISSUE TITLE
Lijsten pagina -> Roze kader?

### ISSUE THREAD

**Issue by CelinexPutte** [luukbrauckmann/look-and-feel-living-styleguide#33]
Waarom staat er een roze kader om het voorbeeld heen?

**Comment by romerdev** [comment]
@CelinexPutte dit is zodat je het onderscheid tussen de witte en grijze achtergrondkleur kunt zien. Ik heb expres een kleur gekozen die niet in de huisstijl staat zodat duidelijk is dat het niet onderdeel is van de lijst. Ik zet er nog een comment onder die dit nog toelicht.
