### ISSUE TITLE
Tekst past niet in border

### ISSUE THREAD

**Issue by IvarSchuyt** [luukbrauckmann/look-and-feel-living-styleguide#6]
https://github.com/luukbrauckmann/look-and-feel-living-styleguide/blob/93c4904396739b2db6a8cf83af2deb48fb9e567b/componenten/formulieren/formulieren.html#L41

Nette styleguide, alleen hier een klein foutje.

**Comment by Stefan-Espant** [comment]
Een oplossing is om in de <code> een overflow-x (horizontale scroll) te geven.
